// ============================================================================
// Fichas de concepto enriquecidas. Cada concepto clave trae:
//  explicación simple · analogía · criterio clave · buena práctica · dato curioso.
// Alimentan Flashcards, el feedback de la práctica y el detalle de nivel.
// ============================================================================
import type { LevelId } from './types';

export interface Concept {
  termino: string;
  level: LevelId;
  explicacion: string;
  analogia: string;
  criterioClave: string;
  buenaPractica: string;
  dato: string;
}

export const CONCEPTS: Concept[] = [
  // ---- Nivel 1 ----
  { termino: 'Machine Learning', level: 1,
    explicacion: 'Sistemas que aprenden patrones desde datos en vez de seguir reglas escritas a mano.',
    analogia: 'Como aprender a cocinar probando muchos platos, no memorizando una sola receta.',
    criterioClave: '¿El comportamiento se aprende de ejemplos? → ML. ¿Son reglas fijas? → software clásico.',
    buenaPractica: 'Empieza por la pregunta y los datos disponibles, no por el modelo de moda.',
    dato: 'El término "Machine Learning" lo acuñó Arthur Samuel en 1959 con un programa que aprendía a jugar damas.' },
  { termino: 'Overfitting', level: 1,
    explicacion: 'El modelo memoriza el entrenamiento y falla con datos nuevos.',
    analogia: 'Como un alumno que memoriza el examen del año pasado pero no entiende la materia.',
    criterioClave: 'Si va excelente en entrenamiento y mal en datos nuevos, sospecha overfitting.',
    buenaPractica: 'Separa train/test, usa validación cruzada y prefiere el modelo más simple que funcione.',
    dato: 'La "navaja de Occam" (preferir lo simple) es el antídoto filosófico del overfitting desde el siglo XIV.' },
  { termino: 'Dataset', level: 1,
    explicacion: 'El conjunto de datos con el que un modelo aprende o se evalúa.',
    analogia: 'Es el "libro de estudio" del modelo: si está mal, aprende mal.',
    criterioClave: 'Calidad y representatividad del dataset > tamaño bruto del modelo.',
    buenaPractica: 'Garbage in, garbage out: limpia y balancea antes de entrenar.',
    dato: 'ImageNet (14M de imágenes etiquetadas) disparó la era del deep learning moderno en 2012.' },
  { termino: 'Inferencia', level: 1,
    explicacion: 'Usar un modelo ya entrenado para producir una predicción o respuesta.',
    analogia: 'Entrenar es estudiar; inferir es rendir el examen.',
    criterioClave: 'El costo recurrente de la IA está en la inferencia, no solo en el entrenamiento.',
    buenaPractica: 'Optimiza latencia y costo por consulta antes de escalar a muchos usuarios.',
    dato: 'Para modelos muy usados, el gasto total de inferencia supera con creces el del entrenamiento.' },

  // ---- Nivel 2 ----
  { termino: 'Token', level: 2,
    explicacion: 'Unidad de texto (palabra o fragmento) con la que trabaja un modelo de lenguaje.',
    analogia: 'Son las "piezas de Lego" del lenguaje para el modelo.',
    criterioClave: 'Costo y límite de contexto se miden en tokens, no en palabras exactas.',
    buenaPractica: 'Sé conciso: menos tokens = menor costo y respuestas más enfocadas.',
    dato: 'En inglés, ~1 token ≈ 4 caracteres ≈ ¾ de palabra; en español suele costar algo más.' },
  { termino: 'Transformer', level: 2,
    explicacion: 'Arquitectura basada en atención que es la base de los LLMs modernos.',
    analogia: 'Lee toda la frase a la vez y decide a qué palabras "prestar atención", como tú al releer.',
    criterioClave: 'La atención permite relacionar palabras lejanas; por eso captan contexto largo.',
    buenaPractica: 'No necesitas implementarlo, pero entender "atención" te ayuda a escribir mejores prompts.',
    dato: 'Nació en el paper de Google "Attention Is All You Need" (2017); la T de GPT es de Transformer.' },
  { termino: 'Context window', level: 2,
    explicacion: 'Cuántos tokens puede "ver" el modelo a la vez en una interacción.',
    analogia: 'Es la memoria de trabajo del modelo: lo que se sale de la ventana, lo olvida.',
    criterioClave: 'Si la conversación es larga, lo viejo puede caerse del contexto y degradar respuestas.',
    buenaPractica: 'Resume o reinyecta lo importante; no asumas que recuerda todo el historial.',
    dato: 'Pasó de ~2k tokens (2020) a más de 1 millón en modelos recientes: un salto de ~500×.' },
  { termino: 'Temperature', level: 2,
    explicacion: 'Parámetro que controla cuánta aleatoriedad/creatividad tiene la salida.',
    analogia: 'Como el volumen de la improvisación: baja = preciso, alta = creativo.',
    criterioClave: 'Datos exactos o código → temperature baja. Lluvia de ideas → alta.',
    buenaPractica: 'Para tareas reproducibles usa 0–0.3; documenta el valor que usaste.',
    dato: 'El nombre viene de la física (distribución de Boltzmann): "calentar" reparte más la probabilidad.' },
  { termino: 'Alucinación', level: 2,
    explicacion: 'Cuando el modelo genera información falsa con total seguridad.',
    analogia: 'Como un estudiante que, por no quedar mal, inventa una respuesta convincente.',
    criterioClave: 'El modelo predice texto plausible, no verdad: todo dato crítico se verifica.',
    buenaPractica: 'Pide fuentes, usa RAG y nunca confíes datos sensibles sin comprobar.',
    dato: '"Alucinación" fue elegida Palabra del Año 2023 por Dictionary.com por el auge de la IA generativa.' },
  { termino: 'Embedding', level: 5,
    explicacion: 'Vector numérico que representa el significado de un texto.',
    analogia: 'Un "GPS del significado": ideas parecidas quedan cerca en el mapa.',
    criterioClave: 'Es la base de la búsqueda semántica y del RAG.',
    buenaPractica: 'Usa el mismo modelo de embeddings para indexar y para consultar.',
    dato: 'Con vectores, "rey - hombre + mujer ≈ reina": la semántica se vuelve aritmética.' },

  // ---- Nivel 3 ----
  { termino: 'NotebookLM', level: 3,
    explicacion: 'Herramienta que razona solo sobre las fuentes que tú cargas.',
    analogia: 'Un asistente que solo te responde con el libro que le diste, no con rumores.',
    criterioClave: 'Ideal cuando necesitas respuestas ancladas a tus documentos, sin invención.',
    buenaPractica: 'Súbele material confiable y pídele que cite el fragmento de origen.',
    dato: 'Su función de "podcast" genera una conversación de audio a partir de tus documentos.' },
  { termino: 'Obsidian', level: 3,
    explicacion: 'App de notas Markdown locales conectadas por enlaces ([[wikilinks]]).',
    analogia: 'Un "segundo cerebro": cada nota es una neurona y los enlaces, las sinapsis.',
    criterioClave: 'Conocimiento permanente y enlazado → Obsidian; gestión colaborativa → Notion.',
    buenaPractica: 'Captura → resume → enlaza → convierte en nota permanente, prompt o producto.',
    dato: 'Tus notas son archivos .md en tu disco: sin lock-in, las lees aunque la app desaparezca.' },
  { termino: 'Perplexity', level: 3,
    explicacion: 'Asistente de búsqueda que responde con fuentes web y citas verificables.',
    analogia: 'Un bibliotecario que te da la respuesta y, además, el libro y la página.',
    criterioClave: 'Para hechos recientes con trazabilidad, prioriza herramientas con citas.',
    buenaPractica: 'Verifica las fuentes citadas; no todas las citas son igual de confiables.',
    dato: 'Popularizó el formato "respuesta + fuentes" que hoy copian muchos buscadores con IA.' },

  // ---- Nivel 4 ----
  { termino: 'System instruction', level: 4,
    explicacion: 'Instrucción de alto nivel que fija el rol y comportamiento del asistente.',
    analogia: 'El "manual del puesto" que lee el empleado antes de atender a cada cliente.',
    criterioClave: 'Define rol, tono y reglas una vez, en vez de repetirlas en cada mensaje.',
    buenaPractica: 'Sé explícito en formato, límites y qué hacer ante dudas o falta de datos.',
    dato: 'Un buen system prompt suele mejorar más la calidad que cambiar de modelo.' },
  { termino: 'Few-shot', level: 4,
    explicacion: 'Dar 2–3 ejemplos dentro del prompt para guiar el formato de respuesta.',
    analogia: 'Mostrar muestras de trabajo a un nuevo empleado antes de pedirle la tarea.',
    criterioClave: 'Si el formato importa o el zero-shot falla, agrega ejemplos.',
    buenaPractica: 'Usa ejemplos representativos y variados; ejemplos sesgados sesgan la salida.',
    dato: 'GPT-3 (2020) se tituló literalmente "Language Models are Few-Shot Learners".' },
  { termino: 'Chain-of-thought', level: 4,
    explicacion: 'Pedir al modelo que razone paso a paso antes de responder.',
    analogia: 'Como "muestra tu procedimiento" en un examen de matemáticas.',
    criterioClave: 'Útil en problemas de varios pasos (lógica, cálculo, planeación).',
    buenaPractica: 'Pide el razonamiento y luego una respuesta final clara y separada.',
    dato: 'Solo agregar "pensemos paso a paso" elevó la precisión en problemas de lógica de forma notable (2022).' },
  { termino: 'PromptOps', level: 4,
    explicacion: 'Gestionar los prompts como activos: versionarlos, probarlos, medirlos y reutilizarlos.',
    analogia: 'Tratar tus prompts como código: con control de versiones y pruebas.',
    criterioClave: 'Si un prompt es clave para tu negocio, no debe vivir suelto en un chat.',
    buenaPractica: 'Guarda prompts en plantillas versionadas con casos de prueba y métricas.',
    dato: 'Empresas ya tienen "prompt libraries" internas tratadas como propiedad intelectual.' },

  // ---- Nivel 5 ----
  { termino: 'RAG', level: 5,
    explicacion: 'Recuperar fragmentos de tus documentos y usarlos como contexto para responder.',
    analogia: 'Examen a libro abierto: el modelo consulta tus apuntes antes de contestar.',
    criterioClave: 'Conocimiento que cambia y debe citarse → RAG; estilo/comportamiento fijo → fine-tuning.',
    buenaPractica: 'Cuida chunking y reranking; un mal recuperador arruina hasta el mejor modelo.',
    dato: 'El término "RAG" lo introdujo un paper de Facebook AI en 2020.' },
  { termino: 'Chunking', level: 5,
    explicacion: 'Dividir documentos en fragmentos manejables para indexarlos en RAG.',
    analogia: 'Cortar un libro en fichas: ni una sola página gigante ni mil pedacitos sin sentido.',
    criterioClave: 'Chunks muy grandes traen ruido; muy chicos pierden contexto.',
    buenaPractica: 'Respeta límites naturales (secciones, párrafos) y usa solapamiento moderado.',
    dato: 'El tamaño de chunk suele importar más para la calidad del RAG que el propio LLM.' },
  { termino: 'Vector database', level: 5,
    explicacion: 'Base de datos que almacena embeddings y busca por similitud (significado).',
    analogia: 'Una biblioteca ordenada por "de qué trata", no por orden alfabético.',
    criterioClave: 'Necesaria cuando buscas por significado a gran escala, no por palabra exacta.',
    buenaPractica: 'Combina búsqueda semántica + léxica (híbrida) para mejores resultados.',
    dato: 'La búsqueda por vecinos cercanos en millones de vectores tarda milisegundos con índices ANN.' },
  { termino: 'Reranking', level: 5,
    explicacion: 'Reordenar los fragmentos recuperados por relevancia real antes de pasarlos al modelo.',
    analogia: 'Un editor que, de 20 recortes, elige y ordena los 3 que de verdad sirven.',
    criterioClave: 'Si el RAG trae contexto irrelevante, casi siempre falta reranking.',
    buenaPractica: 'Recupera muchos candidatos y deja que el reranker se quede con los mejores.',
    dato: 'Añadir un reranker suele mejorar más la respuesta que cambiar el modelo generador.' },

  // ---- Nivel 6 ----
  { termino: 'Fine-tuning', level: 6,
    explicacion: 'Ajustar los pesos de un modelo con datos propios para especializarlo.',
    analogia: 'Tomar un profesional generalista y darle una especialización con casos tuyos.',
    criterioClave: 'Cambia estilo/comportamiento fijo; para conocimiento que cambia, usa RAG.',
    buenaPractica: 'Prueba primero prompting y RAG; haz fine-tuning solo si realmente hace falta.',
    dato: 'Casi todos los asistentes actuales son un modelo base + un ajuste fino de instrucciones.' },
  { termino: 'LoRA', level: 6,
    explicacion: 'Fine-tuning eficiente que entrena muy pocos parámetros extra.',
    analogia: 'En vez de reescribir el libro, le pegas anotaciones en los márgenes.',
    criterioClave: 'Ideal con poco cómputo o cuando quieres muchos "adaptadores" intercambiables.',
    buenaPractica: 'Guarda el adaptador aparte del modelo base: ocupa MB en vez de GB.',
    dato: 'Un adaptador LoRA puede pesar miles de veces menos que el modelo completo.' },
  { termino: 'Recall', level: 6,
    explicacion: 'De los positivos reales, qué porcentaje detecta el modelo.',
    analogia: 'En un control de seguridad: ¿cuántos riesgos reales NO se te escaparon?',
    criterioClave: 'Prioriza recall cuando un falso negativo es peligroso (salud, seguridad).',
    buenaPractica: 'Reporta recall junto a precision; subir uno suele bajar el otro.',
    dato: 'En un detector de cáncer, un recall bajo significa enfermos que pasan inadvertidos: inaceptable.' },
  { termino: 'Accuracy', level: 6,
    explicacion: 'Proporción de predicciones correctas sobre el total.',
    analogia: 'La "nota global", que puede ocultar que reprobaste un tema clave.',
    criterioClave: 'Con clases desbalanceadas, la accuracy engaña: mira F1/recall.',
    buenaPractica: 'Nunca uses accuracy sola en problemas raros (fraude, fallas, enfermedades).',
    dato: 'Si el 99% de los casos son "normales", predecir siempre "normal" da 99% de accuracy y 0 utilidad.' },

  // ---- Nivel 7 ----
  { termino: 'Agente IA', level: 7,
    explicacion: 'Sistema que planifica, usa herramientas y ejecuta tareas de varios pasos.',
    analogia: 'Un becario proactivo: no solo responde, busca, calcula y actúa hasta terminar.',
    criterioClave: 'Tarea de un paso → un prompt basta; flujo multi-paso con herramientas → agente.',
    buenaPractica: 'Dale límites, logs y aprobación humana antes de acciones irreversibles.',
    dato: '2025 fue bautizado por la industria como "el año de los agentes".' },
  { termino: 'MCP', level: 7,
    explicacion: 'Protocolo estándar para conectar modelos con herramientas y datos externos.',
    analogia: 'El "USB-C" de la IA: un mismo conector para muchas herramientas.',
    criterioClave: 'Útil cuando quieres reutilizar integraciones entre distintos agentes/apps.',
    buenaPractica: 'Expón solo las herramientas necesarias y con permisos mínimos.',
    dato: 'Anthropic lo lanzó a finales de 2024 y fue adoptado por todo el ecosistema en meses.' },
  { termino: 'Human-in-the-loop', level: 7,
    explicacion: 'Mantener supervisión humana en pasos críticos del flujo de IA.',
    analogia: 'El copiloto sugiere la maniobra, pero el comandante aprueba el aterrizaje.',
    criterioClave: 'Acción irreversible o de alto impacto → siempre aprobación humana.',
    buenaPractica: 'El agente propone y explica; el humano confirma y queda registrado en logs.',
    dato: 'Muchos incidentes de IA en producción se evitan con un simple "¿confirmas?" antes de ejecutar.' },
  { termino: 'Guardrail', level: 7,
    explicacion: 'Regla o control que limita qué puede decir o hacer un agente.',
    analogia: 'Las barreras de una autopista: no conducen por ti, pero evitan que te despeñes.',
    criterioClave: 'A más autonomía y permisos del agente, más guardrails necesitas.',
    buenaPractica: 'Combina límites de temas, de permisos y validación de salidas.',
    dato: 'Un guardrail típico bloquea que el modelo revele su propio system prompt.' },

  // ---- Nivel 8 ----
  { termino: 'Vibe coding', level: 8,
    explicacion: 'Dirigir a la IA con lenguaje natural para construir software rápido, con criterio.',
    analogia: 'Pasas de albañil a arquitecto: describes la obra y revisas que esté bien hecha.',
    criterioClave: 'No es improvisar: sin spec ni revisión, acumulas deuda y bugs.',
    buenaPractica: 'Flujo: problema → spec → app base → revisar código → probar → desplegar.',
    dato: 'El término "vibe coding" lo popularizó Andrej Karpathy en 2025.' },
  { termino: 'Webhook', level: 8,
    explicacion: 'Endpoint que recibe un evento externo y dispara un flujo automático.',
    analogia: 'El timbre de tu casa: alguien llega (evento) y suena la acción.',
    criterioClave: 'Úsalo para reaccionar a eventos en tiempo real, en vez de estar consultando.',
    buenaPractica: 'Valida el origen del webhook y maneja reintentos ante fallos.',
    dato: 'Webhooks vs. polling: esperar el aviso es mucho más eficiente que preguntar "¿ya?" cada minuto.' },
  { termino: 'n8n', level: 8,
    explicacion: 'Plataforma de automatización visual por nodos, autoalojable.',
    analogia: 'Un tablero de dominó digital: conectas piezas y el evento las dispara en cadena.',
    criterioClave: 'Self-hosting y control de datos → n8n; simplicidad cloud → Make/Zapier.',
    buenaPractica: 'Empieza con un flujo pequeño end-to-end antes de orquestar todo.',
    dato: 'La "n8n" significa "nodemation" (node + automation).' },

  // ---- Nivel 9 ----
  { termino: 'Computer Vision', level: 9,
    explicacion: 'IA para interpretar imágenes y video (clasificar, detectar, segmentar).',
    analogia: 'Darle "ojos" y entendimiento visual a la máquina.',
    criterioClave: 'Si el problema es sobre lo que se ve (objetos, zonas, defectos), es visión.',
    buenaPractica: 'El cuello de botella suele ser el etiquetado de datos, no el modelo.',
    dato: 'Es el corazón de VisionPro: detectar EPP, maquinaria y riesgos en obra.' },
  { termino: 'YOLO', level: 9,
    explicacion: 'Familia de modelos de detección de objetos en tiempo real.',
    analogia: 'Una sola mirada que ubica todo a la vez, en lugar de revisar zona por zona.',
    criterioClave: 'Ideal para video en vivo donde importa la velocidad (FPS).',
    buenaPractica: 'Equilibra precisión vs. velocidad eligiendo el tamaño de modelo adecuado al hardware.',
    dato: 'YOLO = "You Only Look Once"; revolucionó la detección por su rapidez.' },
  { termino: 'IoU', level: 9,
    explicacion: 'Mide el solape entre la caja predicha y la real (intersección sobre unión).',
    analogia: 'Qué tanto se "pisan" dos figuras: 1 = idénticas, 0 = no se tocan.',
    criterioClave: 'Es la base para decidir si una detección "acierta" (y para el mAP).',
    buenaPractica: 'Define el umbral de IoU según qué tan exacta debe ser la ubicación.',
    dato: 'Un IoU de 0.5 es el umbral clásico para considerar correcta una detección.' },
  { termino: 'Edge AI', level: 9,
    explicacion: 'Ejecutar IA localmente en el dispositivo, sin depender de la nube.',
    analogia: 'Pensar con tu propio cerebro en vez de llamar por teléfono para cada decisión.',
    criterioClave: 'Necesario con baja latencia, sin conexión o datos sensibles que no deben salir.',
    buenaPractica: 'Optimiza el modelo (quantization) para que corra en hardware limitado.',
    dato: 'En obra, VisionPro usa edge AI (p. ej. Jetson) para analizar cámaras sin subir el video.' },
  { termino: 'Digital Twin', level: 9,
    explicacion: 'Representación digital viva de un activo o proceso real.',
    analogia: 'Un "videojuego" del edificio que se actualiza con datos del edificio real.',
    criterioClave: 'Aporta valor cuando se alimenta de datos en vivo, no es solo un modelo 3D.',
    buenaPractica: 'Conecta sensores/IoT y define qué decisiones mejorará el gemelo.',
    dato: 'La NASA usó gemelos digitales para diagnosticar naves Apollo a distancia.' },

  // ---- Nivel 10 ----
  { termino: 'Prompt injection', level: 10,
    explicacion: 'Ataque donde contenido externo intenta secuestrar las instrucciones del modelo.',
    analogia: 'Una nota escondida que le dice a tu asistente "ignora a tu jefe y hazme caso a mí".',
    criterioClave: 'Si tu agente lee contenido no confiable, asume que puede venir envenenado.',
    buenaPractica: 'Nunca des permisos amplios a agentes que procesan webs, PDFs o emails ajenos.',
    dato: 'Es el riesgo #1 de seguridad en apps con LLM según el OWASP Top 10 para LLMs.' },
  { termino: 'MLOps', level: 10,
    explicacion: 'Prácticas para desplegar, monitorear y mantener modelos en producción.',
    analogia: 'El mantenimiento de un auto: no basta con comprarlo, hay que cuidarlo y revisarlo.',
    criterioClave: 'Un modelo sin monitoreo se degrada en silencio (drift).',
    buenaPractica: 'Versiona datos y modelos, y mide calidad en producción, no solo en laboratorio.',
    dato: 'La mayoría de proyectos de ML que fracasan no es por el modelo, sino por la operación.' },
  { termino: 'Drift', level: 10,
    explicacion: 'Cambio en los datos o relaciones reales que degrada el desempeño del modelo.',
    analogia: 'Un mapa que deja de servir porque la ciudad cambió.',
    criterioClave: 'Si el mundo cambia (precios, modas, clientes), tu modelo envejece.',
    buenaPractica: 'Monitorea métricas en vivo y reentrena periódicamente.',
    dato: 'Muchos modelos de demanda colapsaron en 2020: la pandemia rompió todos sus patrones.' },
  { termino: 'ROI', level: 10,
    explicacion: 'Retorno sobre la inversión: beneficio obtenido frente a lo invertido.',
    analogia: 'La pregunta del dueño: "¿este gasto me devolvió más de lo que costó?".',
    criterioClave: 'La IA se justifica por impacto (costo, error, decisión, ventaja), no por moda.',
    buenaPractica: 'Define la métrica de éxito y el ROI esperado antes de construir.',
    dato: 'La pregunta estratégica no es "¿qué herramienta uso?" sino "¿qué proceso mejora y cuánto?".' },
];

const map = new Map(CONCEPTS.map((c) => [c.termino.toLowerCase(), c]));
export const getConcept = (termino: string): Concept | undefined => map.get(termino.toLowerCase());
export const conceptsByLevel = (level: LevelId): Concept[] => CONCEPTS.filter((c) => c.level === level);
