// ============================================================================
// Glosario de IA, productividad y AEC — tomado del vault de Alejandro Palpan
// (05_KNOWLEDGE/20_Glosario_150_Terminos). Cada término se asigna a un nivel.
// ============================================================================
import type { GlossaryTerm } from './types';

export const GLOSSARY: GlossaryTerm[] = [
  { n: 1, termino: 'Inteligencia Artificial', definicion: 'Campo que permite a sistemas ejecutar tareas cognitivas como percepción, lenguaje, aprendizaje, planificación y decisión.', nivel: 1 },
  { n: 2, termino: 'Machine Learning', definicion: 'Subcampo de IA donde los modelos aprenden patrones desde datos.', nivel: 1 },
  { n: 3, termino: 'Deep Learning', definicion: 'Machine Learning con redes neuronales profundas.', nivel: 1 },
  { n: 4, termino: 'Red neuronal', definicion: 'Modelo compuesto por capas de neuronas artificiales conectadas por pesos.', nivel: 1 },
  { n: 5, termino: 'Parámetro', definicion: 'Valor interno aprendido por el modelo durante el entrenamiento.', nivel: 1 },
  { n: 6, termino: 'Hiperparámetro', definicion: 'Valor definido por humanos antes o durante el entrenamiento, como el learning rate.', nivel: 6 },
  { n: 7, termino: 'Dataset', definicion: 'Conjunto de datos usado para entrenar o evaluar modelos.', nivel: 1 },
  { n: 8, termino: 'Feature', definicion: 'Variable de entrada usada por el modelo.', nivel: 1 },
  { n: 9, termino: 'Label', definicion: 'Respuesta correcta o variable objetivo en aprendizaje supervisado.', nivel: 1 },
  { n: 10, termino: 'Entrenamiento', definicion: 'Proceso de ajustar los parámetros del modelo usando datos.', nivel: 1 },
  { n: 11, termino: 'Inferencia', definicion: 'Uso del modelo entrenado para producir una predicción o salida.', nivel: 1 },
  { n: 12, termino: 'Overfitting', definicion: 'Cuando el modelo memoriza el entrenamiento y falla con datos nuevos.', nivel: 1 },
  { n: 13, termino: 'Underfitting', definicion: 'Cuando el modelo es demasiado simple para aprender el patrón.', nivel: 6 },
  { n: 14, termino: 'Validación cruzada', definicion: 'Técnica para estimar desempeño en datos no vistos.', nivel: 6 },
  { n: 15, termino: 'Métrica', definicion: 'Medida para evaluar la calidad del modelo o sistema.', nivel: 6 },
  { n: 16, termino: 'Accuracy', definicion: 'Proporción de predicciones correctas.', nivel: 6 },
  { n: 17, termino: 'Precision', definicion: 'De las predicciones positivas, cuántas son correctas.', nivel: 6 },
  { n: 18, termino: 'Recall', definicion: 'De los positivos reales, cuántos detecta el modelo.', nivel: 6 },
  { n: 19, termino: 'F1-score', definicion: 'Promedio balanceado entre precision y recall.', nivel: 6 },
  { n: 20, termino: 'AUC', definicion: 'Capacidad de separar clases en distintos umbrales.', nivel: 6 },
  { n: 21, termino: 'Computer Vision', definicion: 'IA para interpretar imágenes y video.', nivel: 9 },
  { n: 22, termino: 'Detección de objetos', definicion: 'Identificar objetos y ubicarlos con bounding boxes.', nivel: 9 },
  { n: 23, termino: 'Segmentación', definicion: 'Asignar una clase a cada pixel o región.', nivel: 9 },
  { n: 24, termino: 'YOLO', definicion: 'Familia de modelos para detección de objetos en tiempo real.', nivel: 9 },
  { n: 25, termino: 'CNN', definicion: 'Red neuronal convolucional usada en visión por computadora.', nivel: 9 },
  { n: 26, termino: 'Transformer', definicion: 'Arquitectura basada en atención usada en LLMs y modelos multimodales.', nivel: 2 },
  { n: 27, termino: 'Attention', definicion: 'Mecanismo que pondera qué partes del contexto son más relevantes.', nivel: 2 },
  { n: 28, termino: 'Token', definicion: 'Unidad de texto que procesa un modelo de lenguaje.', nivel: 2 },
  { n: 29, termino: 'Tokenización', definicion: 'Proceso de dividir texto en tokens.', nivel: 2 },
  { n: 30, termino: 'Embedding', definicion: 'Vector numérico que representa significado o características.', nivel: 5 },
  { n: 31, termino: 'LLM', definicion: 'Large Language Model entrenado para procesar y generar lenguaje.', nivel: 2 },
  { n: 32, termino: 'IA generativa', definicion: 'IA capaz de crear texto, imagen, audio, video o código.', nivel: 2 },
  { n: 33, termino: 'Prompt', definicion: 'Instrucción dada a un modelo.', nivel: 4 },
  { n: 34, termino: 'Prompt Engineering', definicion: 'Diseño de prompts para obtener mejores resultados.', nivel: 4 },
  { n: 35, termino: 'PromptOps', definicion: 'Gestión, versionado y evaluación de prompts.', nivel: 4 },
  { n: 36, termino: 'System instruction', definicion: 'Instrucción de alto nivel que define el comportamiento del asistente.', nivel: 4 },
  { n: 37, termino: 'Temperature', definicion: 'Parámetro que controla la aleatoriedad de la salida.', nivel: 2 },
  { n: 38, termino: 'Top-p', definicion: 'Parámetro de muestreo que limita opciones por probabilidad acumulada.', nivel: 2 },
  { n: 39, termino: 'Context window', definicion: 'Cantidad de tokens visibles para el modelo en una interacción.', nivel: 2 },
  { n: 40, termino: 'RAG', definicion: 'Retrieval-Augmented Generation: generación aumentada con documentos recuperados.', nivel: 5 },
  { n: 41, termino: 'Retriever', definicion: 'Componente que busca fragmentos relevantes.', nivel: 5 },
  { n: 42, termino: 'Vector database', definicion: 'Base para almacenar y buscar embeddings.', nivel: 5 },
  { n: 43, termino: 'Chunking', definicion: 'División de documentos en fragmentos para indexación.', nivel: 5 },
  { n: 44, termino: 'Reranking', definicion: 'Reordenamiento de resultados recuperados por relevancia.', nivel: 5 },
  { n: 45, termino: 'Fine-tuning', definicion: 'Ajuste de los pesos de un modelo con datos específicos.', nivel: 6 },
  { n: 46, termino: 'LoRA', definicion: 'Técnica eficiente de fine-tuning con menos parámetros entrenables.', nivel: 6 },
  { n: 47, termino: 'Agente IA', definicion: 'Sistema que planifica, usa herramientas y ejecuta tareas multi-paso.', nivel: 7 },
  { n: 48, termino: 'Tool use', definicion: 'Capacidad del modelo de invocar herramientas externas.', nivel: 7 },
  { n: 49, termino: 'Function calling', definicion: 'Invocación estructurada de funciones por parte del modelo.', nivel: 7 },
  { n: 50, termino: 'MCP', definicion: 'Model Context Protocol para conectar modelos con herramientas y datos.', nivel: 7 },
  { n: 51, termino: 'Human-in-the-loop', definicion: 'Supervisión humana dentro del flujo de IA.', nivel: 7 },
  { n: 52, termino: 'Guardrail', definicion: 'Regla o control para limitar salidas o acciones de IA.', nivel: 7 },
  { n: 53, termino: 'Prompt injection', definicion: 'Ataque que intenta cambiar las instrucciones del modelo mediante contenido externo.', nivel: 10 },
  { n: 54, termino: 'MLOps', definicion: 'Prácticas para desplegar, monitorear y mantener modelos en producción.', nivel: 10 },
  { n: 55, termino: 'Drift', definicion: 'Cambio en datos o relaciones que degrada el desempeño del modelo.', nivel: 10 },
  { n: 56, termino: 'Data governance', definicion: 'Gestión de calidad, permisos, linaje y uso de datos.', nivel: 10 },
  { n: 57, termino: 'Multimodal', definicion: 'Modelo que trabaja con varias modalidades como texto e imagen.', nivel: 2 },
  { n: 58, termino: 'Edge AI', definicion: 'IA ejecutada en dispositivos locales como una Jetson.', nivel: 9 },
  { n: 59, termino: 'Inference latency', definicion: 'Tiempo que tarda un modelo en responder.', nivel: 6 },
  { n: 60, termino: 'Cost per query', definicion: 'Costo por consulta de IA.', nivel: 10 },
  { n: 61, termino: 'AgentFlow', definicion: 'Plataforma/arquitectura para flujos con agentes IA.', nivel: 7 },
  { n: 62, termino: 'Vibe coding', definicion: 'Desarrollo de software guiado por lenguaje natural e IA.', nivel: 8 },
  { n: 63, termino: 'Codex', definicion: 'Agente de codificación de OpenAI.', nivel: 8 },
  { n: 64, termino: 'Claude Code', definicion: 'Agente de codificación de Anthropic.', nivel: 8 },
  { n: 65, termino: 'v0', definicion: 'Herramienta de Vercel para generar interfaces y apps con IA.', nivel: 8 },
  { n: 66, termino: 'n8n', definicion: 'Plataforma de automatización visual y workflows.', nivel: 8 },
  { n: 67, termino: 'Webhook', definicion: 'Endpoint que recibe eventos externos.', nivel: 8 },
  { n: 68, termino: 'API', definicion: 'Interfaz para que sistemas intercambien datos o acciones.', nivel: 8 },
  { n: 69, termino: 'CDE', definicion: 'Common Data Environment: entorno común de datos del proyecto.', nivel: 9 },
  { n: 70, termino: 'BIM', definicion: 'Building Information Modeling.', nivel: 9 },
  { n: 71, termino: 'Digital Twin', definicion: 'Representación digital viva de un activo o proceso.', nivel: 9 },
  { n: 72, termino: 'VisionPro', definicion: 'Plataforma de inteligencia visual para obras.', nivel: 9 },
  { n: 73, termino: 'mAP', definicion: 'Métrica de calidad para detección de objetos.', nivel: 9 },
  { n: 74, termino: 'IoU', definicion: 'Intersección sobre unión, mide el solape de cajas o segmentos.', nivel: 9 },
  { n: 75, termino: 'OCR', definicion: 'Reconocimiento óptico de caracteres.', nivel: 9 },
  { n: 76, termino: 'Dashboard', definicion: 'Interfaz visual para monitorear datos y decisiones.', nivel: 9 },
  { n: 77, termino: 'KPI', definicion: 'Indicador clave de desempeño.', nivel: 9 },
  { n: 78, termino: 'ROI', definicion: 'Retorno sobre la inversión.', nivel: 10 },
  { n: 79, termino: 'TCO', definicion: 'Costo total de propiedad.', nivel: 10 },
  { n: 80, termino: 'ETL', definicion: 'Extracción, transformación y carga de datos.', nivel: 9 },
  { n: 81, termino: 'Semantic search', definicion: 'Búsqueda por significado.', nivel: 5 },
  { n: 82, termino: 'Hybrid search', definicion: 'Búsqueda que combina léxica (BM25) y semántica.', nivel: 5 },
  { n: 83, termino: 'Knowledge graph', definicion: 'Grafo de entidades y relaciones.', nivel: 5 },
  { n: 84, termino: 'Chain-of-thought', definicion: 'Razonamiento paso a paso, normalmente interno o resumido.', nivel: 4 },
  { n: 85, termino: 'Self-consistency', definicion: 'Generar varias respuestas y elegir la más consistente.', nivel: 4 },
  { n: 86, termino: 'Test-time compute', definicion: 'Más cómputo durante la respuesta para mejorar el razonamiento.', nivel: 4 },
  { n: 87, termino: 'Caching', definicion: 'Reuso de resultados para reducir costo y latencia.', nivel: 8 },
  { n: 88, termino: 'Rate limit', definicion: 'Límite de uso por unidad de tiempo.', nivel: 8 },
  { n: 89, termino: 'Observability', definicion: 'Capacidad de monitorear el sistema con logs, métricas y traces.', nivel: 10 },
  { n: 90, termino: 'PII', definicion: 'Información personal identificable.', nivel: 10 },
  { n: 91, termino: 'EU AI Act', definicion: 'Regulación europea sobre IA.', nivel: 10 },
  { n: 92, termino: 'C2PA', definicion: 'Estándar de procedencia de contenido digital.', nivel: 10 },
  { n: 93, termino: 'Open-weight model', definicion: 'Modelo cuyos pesos están disponibles bajo licencia.', nivel: 10 },
  { n: 94, termino: 'Closed model', definicion: 'Modelo propietario sin acceso a los pesos.', nivel: 10 },
  { n: 95, termino: 'Quantization', definicion: 'Reducción de precisión para acelerar la inferencia.', nivel: 6 },
  { n: 96, termino: 'Distillation', definicion: 'Transferencia de conocimiento de un modelo grande a uno pequeño.', nivel: 6 },
  { n: 97, termino: 'GPU', definicion: 'Procesador paralelo útil para operaciones con matrices.', nivel: 6 },
  { n: 98, termino: 'Python', definicion: 'Lenguaje principal para IA y automatización.', nivel: 1 },
  { n: 99, termino: 'Jupyter', definicion: 'Cuaderno interactivo de código y texto.', nivel: 1 },
  { n: 100, termino: 'Streamlit', definicion: 'Framework para construir dashboards rápidos en Python.', nivel: 9 },
  { n: 101, termino: 'Supabase', definicion: 'Backend con Postgres, autenticación y almacenamiento.', nivel: 5 },
  { n: 102, termino: 'Obsidian', definicion: 'Herramienta de notas Markdown con enlaces.', nivel: 3 },
  { n: 103, termino: 'MOC', definicion: 'Map of Content: índice de conocimiento.', nivel: 3 },
  { n: 104, termino: 'Backlink', definicion: 'Enlace inverso entre notas.', nivel: 3 },
  { n: 105, termino: 'NotebookLM', definicion: 'Herramienta de investigación sobre tus propias fuentes.', nivel: 3 },
  { n: 106, termino: 'Notion', definicion: 'Workspace de documentación y gestión.', nivel: 3 },
  { n: 107, termino: 'Zotero', definicion: 'Gestor de referencias bibliográficas.', nivel: 3 },
  { n: 108, termino: 'Frontmatter', definicion: 'Metadatos YAML al inicio de una nota.', nivel: 3 },
  { n: 109, termino: 'Synthetic data', definicion: 'Datos generados artificialmente.', nivel: 10 },
  { n: 110, termino: 'Human feedback', definicion: 'Retroalimentación humana usada para alinear el modelo.', nivel: 6 },
];

const byLevel = (lvl: number) => GLOSSARY.filter((t) => t.nivel === lvl);
export const glossaryByLevel = byLevel;
export const findTerm = (name: string) => GLOSSARY.find((t) => t.termino.toLowerCase() === name.toLowerCase());
